version: '3'


services:
  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/ssl/
      - ./ca/:/etc/nginx/ssl/ca/
    networks:
      - net
  openssh:
    image: linuxserver/openssh-server
    container_name: openssh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD_ACCESS=true
      - SUDO_ACCESS=true
      - USER_NAME=sshuser
      - USER_PASSWORD=sshuser
    networks:
      - net
  client:
    image: alpine
    container_name: client
      # install ssh client
    # command: sh -c "apk add --no-cache openssh-client &&
    #   mkdir /root/ssh && mkdir -p /root/.ssh && echo -e "Host nginx-proxy\n\tProxyCommand\
    #   openssl s_client -quiet -servername %h -connect %h:443 -cert\
    #   /root/ssh/certs/client-waifu.crt -key\
    #   /root/ssh/certs/client-waifu.key -CAfile\
    #   /root/ssh/ca/component-ca-chain.pem" > /root/.ssh/config && chmod 600\
    #   ~/.ssh/config && echo "Done" && sleep infinity"
    command: sh -c "apk add --no-cache openssh-client && mkdir -p /root/.ssh && echo -e \"Host nginx-proxy\\n\\tProxyCommand openssl s_client -quiet -servername %h -connect %h:443 -cert /root/ssh/certs/client-waifu.crt -key /root/ssh/certs/client-waifu.key -CAfile /root/ssh/ca/component-ca-chain.pem\" > /root/.ssh/config && chmod 600 /root/.ssh/config && echo 'Done' && sleep infinity"
    networks:
      - net
    depends_on:
      - openssh
    volumes:
      - ./certs:/root/ssh/certs/
      - ./ca/:/root/ssh/ca/

networks:
  net:
    driver: bridge

